# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
#  pull_request: # TODO: Split actions
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2.1.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Save Eclipse Distribution (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Linux"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*linux*.zip"

    - name: Save Eclipse Distribution (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Windows"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*win32*.zip"
        
    - name: Save Eclipse Distribution (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse MacOS"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*macosx*.zip"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: updatesite
        path: releng/edu.kit.kastel.sdq.eclipse.grading.updatesite/target/
  
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        ref: gh-pages

    - run: rm -rf updatesite/

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: updatesite
        path: updatesite/

    - name: Commit
      uses: zwaldowski/git-commit-action@v1

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}

